name: Passing Workflow

on:
  push:
  workflow_dispatch:

jobs:
  pass:
    if: github.repository == 'nonexistent-org/nonexistent-repo'
    runs-on: ubuntu-latest
    steps:
      - name: Pass
        run: echo "This workflow passes"
